name: Bug Report
description: Report a bug or unexpected behavior
title: "[BUG]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: Thanks for reporting a bug! Please fill out the details below.

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      options:
        - Critical (crashes, data loss, security)
        - High (major feature broken)
        - Medium (feature partially broken)
        - Low (cosmetic, minor issue)
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: What happened?
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      placeholder: "1.0.0 or commit SHA"

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      options:
        - Development
        - Production
        - Test

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs/Error Messages
      render: shell
