-- AlterTable
ALTER TABLE "Run" ADD COLUMN "views" INTEGER;
ALTER TABLE "Run" ADD COLUMN "likes" INTEGER;
ALTER TABLE "Run" ADD COLUMN "retention" REAL;
ALTER TABLE "Run" ADD COLUMN "postedAt" DATETIME;
